stages:
  - linter
  - tests
  - build
  - publish

linter:
  image: python:3.5.9-alpine
  stage: linter
  tags:
    - docker
  before_script:
    - python -m pip install --upgrade pip && python -m pip install flake8 flake8-builtins flake8-bugbear flake8-import-order flake8-docstrings flake8-quotes
  script:
    - flake8
  only:
    - merge_requests

security_check:
  image: python:3.5.9-alpine
  stage: linter
  tags:
    - docker
  before_script:
    - apk add build-base
    - python -m pip install --upgrade pip
    - python -m pip install pipenv safety
    - pipenv install
    - pipenv lock --requirements > requirements.txt
  script:
    - safety check -r requirements.txt --ignore=39659
  only:
    - merge_requests

tests:
  image: python:3.5.9-alpine
  stage: tests
  tags:
    - docker
  before_script:
    - apk add build-base
    - python -m pip install --upgrade pip
    - python -m pip install pipenv
    - pipenv install --dev
  script:
    - pipenv run pytest
  only:
    - merge_requests

build:
  image: python:3.5.9-alpine
  stage: build
  tags:
    - docker
  before_script:
    - apk add build-base
    - python -m pip install --upgrade pip
    - python -m pip install twine setuptools wheel
  script:
    - python setup.py sdist bdist_wheel
  only:
    - merge_requests

publish:
  image: python:3.5.9-alpine
  stage: publish
  tags:
    - docker
  before_script:
    - apk add build-base
    - python -m pip install --upgrade pip
    - python -m pip install twine setuptools wheel
  script:
    - python setup.py sdist bdist_wheel
    - python -m twine upload dist/*
  only:
    - /^release-.*$/i